# Generated by Django 2.2 on 2022-08-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light_control',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
