# Generated by Django 2.2 on 2022-08-17 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220817_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light_control',
            name='status',
            field=models.TextField(),
        ),
    ]
