# Generated by Django 2.2 on 2022-08-17 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220817_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='light_control',
            old_name='status',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='light_control',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
