# Generated by Django 2.2 on 2022-08-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220817_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='light_control',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
