# Generated by Django 2.2 on 2022-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220817_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='dh_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_dh', models.TextField()),
                ('time_dh', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fan_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_fan', models.TextField()),
                ('time_fan', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='tv_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_tv', models.TextField()),
                ('time_tv', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
